spring:
  application:
    name: swipe-capture-service
  data:
    mongodb:
      database: ${MONGODB_DATABASE_NAME}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
  jpa:
    show-sql: true
  kafka:
    template:
      default-topic: ${KAFKA_DEFAULT_TOPIC}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    default-property-inclusion: non-null

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    '[com.swipe]': DEBUG
    
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
   distribution:
    percentiles-histogram:
     http.server.requests: true
      