server:
  port: 8090
spring:
  application:
    name: api-gateway
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    
logging:
  pattern:
    level: info

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
   distribution:
    percentiles-histogram:
     http.server.requests: true